# Generated by Django 2.0 on 2021-04-21 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20210417_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 5, 30, 11, 544544, tzinfo=utc)),
        ),
    ]
