# Generated by Django 2.0 on 2021-04-21 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20210421_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 5, 49, 21, 883852, tzinfo=utc)),
        ),
    ]
