# Generated by Django 2.0 on 2021-04-22 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0006_auto_20210421_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 18, 18, 14, 633319)),
        ),
    ]
