# Generated by Django 2.0 on 2021-04-23 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0008_auto_20210423_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 17, 15, 23, 557617)),
        ),
    ]
