# Generated by Django 2.0 on 2021-04-24 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0009_auto_20210423_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 3, 33, 38, 475580)),
        ),
    ]
