# Generated by Django 2.0 on 2021-04-25 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0010_auto_20210424_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 17, 41, 31, 546597)),
        ),
    ]
